export const GETALL = "GET_ALL_PHOTOS"
export const ERROR = "ERROR"
export const INC_PAGE = "INC_PAGE"
export const GETTEN = "GETTEN"
export const LOADING = "LOADING"
export const GETY = "GETY"
export const INIT = "INIT"
export const LOADINGALL = "LOADINGALL"